# Git aliases
alias g='git '
alias gm='git merge origin/master --no-ff --no-commit'
alias gco='git checkout '
alias gcb='gco -b '
alias gcf='gco -- '
alias gs='git st -sb'
alias ga='git add '
alias gb='git branch '
alias gbr='git branch -r '
alias gbd='git branch -D '
alias gc='git ci '
alias gca='git ci -a '
alias gdn='git diff -w --numstat '
alias gf='git fetch -p '
alias gfo='git fetch -p origin '
alias gp='git push origin '
alias gu='git pull origin '
alias gt='git tag '
alias grt='git ls-remote --tags'
alias gg='git grep -p -n --full-name '
alias gl="git log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr)%C(bold blue) <%an>%Creset' --abbrev-commit"
alias guc='git reset --soft HEAD^'
alias gst='git stash '
alias gsa='git stash apply '
alias gbt='git branch -u '
alias gd='git diff -w --color --word-diff'
