tput sgr0
BLUE=$(tput setaf 4)
CYAN=$(tput setaf 6)
VIOLET=$(tput setaf 5)
GREEN=$(tput setaf 2)
MAGENTA=$(tput setaf 5)
YELLOW=$(tput setaf 3)
RED=$(tput setaf 1)
ORANGE=$(tput setaf 9)
BOLD=$(tput bold)
RESET=$(tput sgr0)
